# This is a basic workflow to help you get started with Actions

name: CI
on: 
  repository_dispatch:
    types: [my-event]
  
jobs:
  repoBjobs:
    runs-on: [ubuntu-latest]
    steps:
      - name: echo value
        run: |
          echo ${{ github.event.client_payload.var }} > sample
          cat sample
